version: 2
jobs:
  test:
    working_directory: ~/terraform-aws-ecs-service
    docker:
      - image: ruby:2.3.8
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/test.sh
  prerelease:
    working_directory: ~/terraform-aws-ecs-service
    docker:
      - image: ruby:2.3.8
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/prerelease.sh
  release:
    working_directory: ~/terraform-aws-ecs-service
    docker:
      - image: ruby:2.3.8
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/release.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only: master, terraform011
      - prerelease:
          requires:
            - test
          filters:
            branches:
              only: master, terraform011
      - hold:
          type: approval
          requires:
            - prerelease
          filters:
            branches:
              only: master, terraform011
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master, terraform011
